export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";

export const SET_ALL_USERS = "SET_ALL_USERS"; 

export const SET_USER_DETAILS = "SET_USER_DETAILS";
export const SET_FOLLOWERS_DETAILS = "SET_FOLLOWERS_DETAILS";
export const SET_FOLLOWING_DETAILS = "SET_FOLLOWING_DETAILS";
